package com.androidservice.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF0B6B59)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFC7F2E6)
val LightOnPrimaryContainer = Color(0xFF002019)
val LightSecondary = Color(0xFF4D635D)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD0E8DF)
val LightOnSecondaryContainer = Color(0xFF0A1F1A)
val LightTertiary = Color(0xFF49617A)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFD2E4FF)
val LightOnTertiaryContainer = Color(0xFF001C36)
val LightError = Color(0xFFBA1A1A)
val LightBackground = Color(0xFFFAFCFA)
val LightOnBackground = Color(0xFF191C1B)
val LightSurface = Color(0xFFFAFCFA)
val LightOnSurface = Color(0xFF191C1B)
val LightSurfaceContainerLow = Color(0xFFF1F5F2)
val LightSurfaceContainer = Color(0xFFEBEFEC)
val LightSurfaceContainerHigh = Color(0xFFE5E9E6)
val LightSurfaceVariant = Color(0xFFDCE5E1)
val LightOnSurfaceVariant = Color(0xFF404944)
val LightOutline = Color(0xFF707974)

val DarkPrimary = Color(0xFF8AD7C4)
val DarkOnPrimary = Color(0xFF00382E)
val DarkPrimaryContainer = Color(0xFF005144)
val DarkOnPrimaryContainer = Color(0xFFC7F2E6)
val DarkSecondary = Color(0xFFB4CCC3)
val DarkOnSecondary = Color(0xFF203832)
val DarkSecondaryContainer = Color(0xFF364B45)
val DarkOnSecondaryContainer = Color(0xFFD0E8DF)
val DarkTertiary = Color(0xFFB2C8E6)
val DarkOnTertiary = Color(0xFF19324A)
val DarkTertiaryContainer = Color(0xFF314960)
val DarkOnTertiaryContainer = Color(0xFFD2E4FF)
val DarkError = Color(0xFFFFB4AB)
val DarkBackground = Color(0xFF101413)
val DarkOnBackground = Color(0xFFE0E3E1)
val DarkSurface = Color(0xFF101413)
val DarkOnSurface = Color(0xFFE0E3E1)
val DarkSurfaceContainerLow = Color(0xFF181D1B)
val DarkSurfaceContainer = Color(0xFF1C211F)
val DarkSurfaceContainerHigh = Color(0xFF262B29)
val DarkSurfaceVariant = Color(0xFF404944)
val DarkOnSurfaceVariant = Color(0xFFC0C9C4)
val DarkOutline = Color(0xFF8A938E)
